### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by sabrehagen** [trezm/meerkatjs#3]
Hi,

This library looks like it has had a lot of work put into it, but nobody is going to use it if the readme doesn't explain how to use it and what it can do. Can you add some more details there so we can all take advantage of your work?

Cheers!

**Comment by trezm** [comment]
Good point, sounds like a good project for the long weekend, thanks for the heads up!

**Comment by sabrehagen** [comment]
Thanks! :)

**Comment by trezm** [comment]
Added a brief description, I'll try and add some examples later

**Comment by sabrehagen** [comment]
Great, thanks. If in future you could detail things like how the deltas are calculated and where they're stored, and what kind of overhead this incurs it would be very beneficial!

**Comment by trezm** [comment]
Added
